export const UPDATE_ROUTE = 'UPDATE_ROUTE'

export const CLEAR_ROUTE = 'CLEAR_ROUTE'

export const SET_USER_AND_STATE = 'SET_USER_AND_STATE'

export const SET_USER_AUTHS = 'SET_USER_AUTHS'

export const SET_REFRESH_OPTION = 'SET_REFRESH_OPTION'

export const REMOVE_LOGINED = 'REMOVE_LOGINED'

// export const CHANGE_REUSE_LENGTH = 'CHANGE_REUSE_LENGTH'

export const CHANGE_REUSE_TAB = 'CHANGE_REUSE_TAB'