// -----app.actions-----

export const UPDATE_ROUTE = 'UPDATE_ROUTE'
export type UPDATE_ROUTE = typeof UPDATE_ROUTE

export const CLEAR_ROUTE = 'CLEAR_ROUTE'
export type CLEAR_ROUTE = typeof CLEAR_ROUTE

export const SET_USER_AND_STATE = 'SET_USER_AND_STATE'
export type SET_USER_AND_STATE = typeof SET_USER_AND_STATE

export const SET_USER_PERMISSIONS = 'SET_USER_PERMISSIONS'
export type SET_USER_PERMISSIONS = typeof SET_USER_PERMISSIONS

export const REMOVE_LOGINED = 'REMOVE_LOGINED'
export type REMOVE_LOGINED = typeof REMOVE_LOGINED

export const CHANGE_REUSE_TAB = 'CHANGE_REUSE_TAB'
export type CHANGE_REUSE_TAB = typeof CHANGE_REUSE_TAB

export const ADD_READED_MESSAGE = 'ADD_READED_MESSAGE'
export type ADD_READED_MESSAGE = typeof ADD_READED_MESSAGE

export const ADD_UNREAD_MESSAGE = 'ADD_UNREAD_MESSAGE'
export type ADD_UNREAD_MESSAGE = typeof ADD_UNREAD_MESSAGE

export const REMOVE_UNREAD_MESSAGE = 'REMOVE_UNREAD_MESSAGE'
export type REMOVE_UNREAD_MESSAGE = typeof REMOVE_UNREAD_MESSAGE
